### ISSUE TITLE
Failed to activate the atom-facepalm package

### ISSUE THREAD

**Issue by siathalysedI** [varyform/atom-facepalm#2]
[Enter steps to reproduce below:]
1. Update atom from v0.189.0 version to v1.0.0 version
2. Install atom-facepalm package

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [atom-facepalm](https://github.com/varyform/atom-facepalm) package, v0.3.0
### Stack Trace

Failed to activate the atom-facepalm package

```
At Cannot read property 'eachEditorView' of undefined

TypeError: Cannot read property 'eachEditorView' of undefined
  at Facepalm.engage (/Users/dragon/.atom/packages/atom-facepalm/lib/facepalm.coffee:38:34)
  at Facepalm.updateSubscriptions (/Users/dragon/.atom/packages/atom-facepalm/lib/facepalm.coffee:29:8)
  at /Users/dragon/.atom/packages/atom-facepalm/lib/facepalm.coffee:16:48
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:555:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:135:21)
  at Facepalm.on (/Users/dragon/.atom/packages/atom-facepalm/lib/facepalm.coffee:16:17)
  at Object.module.exports.activate (/Users/dragon/.atom/packages/atom-facepalm/lib/facepalm.coffee:50:11)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:362:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
  3x -1:29.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -1:11.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "git-merge-conflicts"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-facepalm, v0.3.0
color-picker, v2.0.7
drupal, v1.8.0
drupal-info-file, v1.5.1
language-drupal, v0.4.2
linter-javac, v0.1.4
minimap, v4.10.0
monokai, v0.14.0
pigments, v0.8.1
travis-ci-status, v0.15.1
vim-mode, v0.54.0

# Dev
No dev packages
```

**Comment by rgbkrk** [comment]
![](http://media.giphy.com/media/HzTYLfsbJqa2Y/giphy.gif)
